version: '3.8'

services:
  kakao_clone_back:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: ${ENV}
    image: kakao_clone_back
    ports:
      - '9000:3000'
    volumes:
      - /usr/src/app/node_modules
      - ./logs:/logs
    depends_on:
      - postgres
    networks:
      - app
    restart: always

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - '5432:5432'
    networks:
      - app
    volumes:
      - ../postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always


networks:
  app:
    external: true
    name: app